Algoritmo "Cadastro completo"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Realizar um cadastro completo
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 21/10/2024
Var
// Seção de Declarações das variáveis 
nome, sobrenome, cidade, sexo, enderoco: caracter
idade: inteiro
rg, cpf:

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 


Fimalgoritmo