algoritmo "Cadastro Básico"
// Função: Cadastrar
var
nome, sobrenome: caracter
idade: inteiro
inicio
// Seção de Comandos 
escreval ("## Sistema de cadastro básico ##")
escreva (" Digite o seu nome:  ")
leia (nome)
limpatela
escreva (" Digite o seu sobrenome: ")
leia (sobrenome)
limpatela
escreva ("Digite a sua idade: ")
leia (idade)
limpatela

escreval
escreval
escreval (nome, " ", sobrenome)
escreval ("idade: ", idade, " anos")

fimalgoritmo
